title: Core Counseling
keywords: counseling, core counseling, hypnotherapy, psychospiritual counseling, core integration, couples therapy, individual therapy, group therapy
baseurl: http://www.corecounseling.com

images: 
    header: /assets/img/header.png
    footer: /assets/img/footer.png

owner: 
    name: Cynthia Moore
    email: cynthia@corecounseling.com
    phone: 510.869.5252
    address: 1676 University Ave. Berkeley, CA 94703

navigation:
    - title: Home
      url: /index.html
    - title: About Cynthia
      url: /cynthia_moore.html
    - title: Core Integration
      url: /core_counseling.html
    - title: Couples
      url: /couples_counseling.html
    - title: Groups
      url: /group_counseling.html
    - title: Quotes
      url: /cynthias_testimonials.html